### PR TITLE
StackOverflow search

### PR DESCRIPTION
**Pull request by callumio**
Adds a command to search StackOverflow, similar to the Google command.

### CODE REVIEW

**Comment by ImmaHarry** [comment]
I think we should have the command merged with the `google.py` cog rather than having a new one.

**Review by ImmaHarry — CHANGES_REQUESTED** [review]
maybe it'd be good to have this in google.py? a new cog seems too much for a single cmd.

**Review by LevaniVashadze — CHANGES_REQUESTED** [review]
like harry said remove the command from here and add it into google.py and rename the command. Need to work on your copy paste skills. Cant forget to change the command name

**Comment by callumio** [comment]
Done

**Review by LevaniVashadze — APPROVED** [review]
good

**Comment by callumio** [comment]
> like harry said remove the command from here and add it into google.py and rename the command. Need to work on your copy paste skills. Cant forget to change the command name

It was likely me just being tired tbh - it wasn't copied and pasted, just referenced.

**Comment by LevaniVashadze** [comment]
tbh stackoverflows search is worse then googles in my opinion i find better results in google the searching in stackoverflow.

**Comment by LevaniVashadze** [comment]
> > like harry said remove the command from here and add it into google.py and rename the command. Need to work on your copy paste skills. Cant forget to change the command name
> 
> It was likely me just being tired tbh - it wasn't copied and pasted, just referenced.
i was just joking. i copy pasted a command once and forgot to change the name but fixed it immediately

**Review by ImmaHarry — APPROVED** [review]
Looks good to me!!

**Comment by JasonLovesDoggo** [comment]
I'm sure we can use an API to make this even better in the future but for now this is perfectly fine

**Review by JasonLovesDoggo — APPROVED** [review]

**Pull request merged**
