### PR TITLE
Added partying emoji for the level up message

### PR DESCRIPTION
**Pull request by OpenSourceSimon**
I have no idea if it works or how to test it, but I thought it is a nice addition to the level up message. I got the code from utils/Fun.py

### CODE REVIEW

**Comment by ImmaHarry** [comment]
I think its a great idea. @LevaniVashadze What say?

**Comment by LevaniVashadze** [comment]
Yeah i saw it but wasnt on pc so when i get on pc i'll test it

**Comment by LevaniVashadze** [comment]
Works now

**Comment by LevaniVashadze** [comment]
If you are interested in how to run the bot yourself and test stuff we will invite you to our dev server

**Pull request merged**
