### PR TITLE
added catfact

### PR DESCRIPTION
**Pull request by japlic**
I added a catfact command

- [x] made it
- [x] tested it

### CODE REVIEW

**Review by LevaniVashadze — CHANGES_REQUESTED** [review]
Why did you remove the other commands? And use the utils function for api reqs

**Comment by japlic** [comment]
anyone

**Comment by LevaniVashadze** [comment]
He sorry for the delays

**Review by LevaniVashadze — CHANGES_REQUESTED** [review]
Can you check the docs if a sub command of a sub command is possible so that the command is /animal cat fact ? Also I assume this is written by chatgpt based on your previous commits. So please test the code.

**Comment by JasonLovesDoggo** [comment]
LGTM

**Comment by LevaniVashadze** [comment]
> LGTM

Why did you merge it?
We had requested changes

**Pull request merged**
