### PR TITLE
YouTube notification when Lewis posts a new video

### PR DESCRIPTION
**Pull request by OpenSourceSimon**
Todo:
- [x] Use the Discord tasks
- [x] Get the YouTube secret from the .env file
- [x] Check if its a new upload

### CODE REVIEW

**Review by ImmaHarry — APPROVED** [review]

**Comment by LevaniVashadze** [comment]
todo:
[ ] Check if its a new upload

**Review by LevaniVashadze — APPROVED** [review]
I approve my own changes lol

**Review by ImmaHarry — APPROVED** [review]
Looks good to me! 👌👌👌

**Comment by LevaniVashadze** [comment]
Gonna merge it then

**Pull request merged**
