### PR TITLE
classic game.py

### PR DESCRIPTION
**Pull request by ExplodeCodeYT**
this is for Ogiroid

### CODE REVIEW

**Comment by ImmaHarry** [comment]
I doubt this will even work with the Discord bot.

**Comment by JasonLovesDoggo** [comment]
Red flag number 1 You are not importing disnake
Red flag number two you are importing pygame...
Red flag number 3 this is a GUI based game... 😂

**Comment by LevaniVashadze** [comment]
Great Game but this is a discord bot lol

**Comment by FreebieII** [comment]
Yeah, uhm... not gonna work with Ogiroid, at all...

**Comment by ImmaHarry** [comment]
> Great Game but this is a discord bot lol

HeLlO eVeRyOnE wElComE bACk TO mY yOOtOoBe ChAnnEL gUYS, tOdAy i WIlL RuN GuI bAsEd CmD oN DiSCoRD wiThouT imporTing ThE lIbRARy! LeTs GO!!! [boy that too too long to type]

**Pull request closed without merging**
