### PR TITLE
Development

### PR DESCRIPTION
**Pull request by JasonLovesDoggo**

### CODE REVIEW

**Comment by JasonLovesDoggo** [comment]
don't merge yet. still needs a DB migration.

**Review by LevaniVashadze — APPROVED** [review]
Lgtm

**Comment by JasonLovesDoggo** [comment]
My guy, It's specifically says don't merge

**Comment by LevaniVashadze** [comment]
i didnt

**Comment by LevaniVashadze** [comment]
i messed up something else

**Comment by LevaniVashadze** [comment]
please check dc

**Pull request merged**
