### PR TITLE
1.8.0

### PR DESCRIPTION
**Pull request by LevaniVashadze**

### CODE REVIEW

**Comment by JasonLovesDoggo** [comment]
Merge conflicts

**Review by LevaniVashadze — COMMENTED** [review]
Reviewed  and looks good to me

**Comment by ImmaHarry** [comment]
> Reviewed  and looks good to me

Let's merge if all looks good to you.

**Review by ImmaHarry — APPROVED** [review]
Looks good to me 🥵

**Review by DWAA1660 — APPROVED** [review]
Amazoning

**Review by JasonLovesDoggo — APPROVED** [review]

**Pull request merged**
