### PR TITLE
Quote image command

### PR DESCRIPTION
**Pull request by OpenSourceSimon**
A command to use my project [ImageQuoteGenerator](https://github.com/OpenSourceSimon/ImageQuoteGenerator). Harry gave me the idea. I don't have experience with Disnake, so feedback is appreciated! I didn't test it, because I don't know how.

### CODE REVIEW

**Comment by ImmaHarry** [comment]
Hey I think this can be implemented in the future 👌, might need to just tweak it around a little. Thanks @OpenSourceSimon!

**Comment by LevaniVashadze** [comment]
Seems like an interesting command for a dc bot but could be implemented

**Comment by LevaniVashadze** [comment]
just would need slight tweaks and i might move it into a different file

**Review by LevaniVashadze — APPROVED** [review]
Gonna merge it now

**Pull request merged**
